In [7]:
import pandas as pd

sensus = {
    'tinggi': [158, 170, 183, 191, 155, 163, 180, 158, 170],
    'jk': ['pria', 'pria', 'pria', 'pria', 'wanita', 'wanita', 'wanita', 'wanita', 'wanita'],
    'berat': [64, 86, 84, 80, 49, 59, 67, 54, 67]
}

sensus_df = pd.DataFrame(sensus)
print(sensus_df)


   tinggi      jk  berat
0     158    pria     64
1     170    pria     86
2     183    pria     84
3     191    pria     80
4     155  wanita     49
5     163  wanita     59
6     180  wanita     67
7     158  wanita     54
8     170  wanita     67


In [11]:
import numpy as np


print(sensus_df.columns)


X_train = np.array(sensus_df[['tinggi', 'jk']])
y_train = np.array(sensus_df['berat'])

print(f'X_train:\n{X_train} \n')
print(f'y_train: {y_train}')



Index(['tinggi', 'jk', 'berat'], dtype='object')
X_train:
[[158 'pria']
 [170 'pria']
 [183 'pria']
 [191 'pria']
 [155 'wanita']
 [163 'wanita']
 [180 'wanita']
 [158 'wanita']
 [170 'wanita']] 

y_train: [64 86 84 80 49 59 67 54 67]


In [19]:
from sklearn.preprocessing import LabelBinarizer
import numpy as np


X_train_transposed = np.array([
    [1, 2, 3, 4],
    ['a', 'b', 'a', 'c']
])

lb = LabelBinarizer()
jk_binarised = lb.fit_transform(X_train_transposed[1])
print(f'jk: {X_train_transposed[1]} \n')
print(f'jk_binarised:\n{jk_binarised}')


jk_binarised = jk_binarised.flatten()
print(f'jk_binarised flattened:\n{jk_binarised}')


jk: ['a' 'b' 'a' 'c'] 

jk_binarised:
[[1 0 0]
 [0 1 0]
 [1 0 0]
 [0 0 1]]
jk_binarised flattened:
[1 0 0 0 1 0 1 0 0 0 0 1]
